os: osx

language: ruby
rvm:
  - 2.6.3

branches:
  only:
    - master

script:
  - make build

deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN

env:
  global:
    secure: 2p8ExPzb8MD+XVeAeg3E0s+cIXjbxRls5SZS7St7DW/BjJEOUM/NIDkOFUTKfRUkwKJ90WYQUsAGEX2aVz5U4tBI0LFVhPjBNDSBD7V+MhzD4bJc0l4VPzcTo1oiI74Z7lLGDZ/zEUuGDzT0kpVjoKc6+dKzioZJXq4trmdRvBCulzGiWozsuJHMW0x4pT6lnJNTkhLI0er4/+gvB+s5hcN2elytyYD5LyERBLObpCNyrWAxLdAOKNtIy/hc9qJe0YofG3ZKDrPMC/kozUW0YyuOUTqaJNR+BtsDCbeCjTj0w+KxxPiZjv1NVPaDtY4o082pzfHC/y4hvLHhnqqwe47hSNEro6pO8KFTn/XXJuFhAW3uo/BgEYC8XylfPF9qYpjM7n70FtNLMqvdStJMslkWEHAJWpT+KAJm0EZFD+mIEdc4rEdA5eY3QtWr+rnIMZmvvbKFUVrC4inXcgkOOmwYvY6FgpdEzHmqpZLXemlPP0w24seGD5dg1IzQIRgjZqr0VwnwGDDOvQA1GC5BGiBaHXrrFgcaZrSC2tgknKH4Eira4lP4dO7oxRk2z8hkzOexlqPcdeV2E3wnXBy82u97sPRgkPcZ7XVEBVSChvxQlBhqcJ7hbUZ1TUZZ3g84N2l5NnwLrllmbjt42vqe1UUasfoh8cZwUer/xtq9luQ=

notifications:
  email: false
