title: Blog by Ivan Ukhov
email: ivan.ukhov@gmail.com
description: She sells seashells on the seashore.
baseurl:
url: https://blog.ivanukhov.com
twitter_username: IvanUkhov
github_username: IvanUkhov

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
