title: Good news, everyone!
author: Ivan Ukhov
email: ivan.ukhov@gmail.com
description: She sells seashells by the seashore.
url: https://blog.ivanukhov.com
twitter_username: IvanUkhov
github_username: IvanUkhov

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
