title: Good news, everyone!
author: Ivan Ukhov
email: ivan.ukhov@gmail.com
description: Notes about pragmatic data science
url: https://blog.ivanukhov.com

github_username: IvanUkhov
linkedin_username: IvanUkhov
twitter_username: IvanUkhov

google_analytics: UA-47932672-9

disqus: {shortname: good-news-everyone}
markdown: kramdown
show_excerpts: true
theme: minima

plugins:
  - jekyll-feed
