title: Good news, everyone!
author: Ivan Ukhov
email: ivan.ukhov@gmail.com
description: On to data science
url: https://blog.ivanukhov.com

github_username: IvanUkhov
linkedin_username: IvanUkhov
twitter_username: IvanUkhov

disqus:
  shortname: good-news-everyone

exclude:
  - '*.Rmd'
  - .rstudio
  - _caches
  - _scripts

future: true
markdown: kramdown
show_excerpts: true
theme: minima

minima:
  date_format: '%B %-d, %Y'

plugins:
  - jekyll-feed
