title: Good news, everyone!
author:
  name: Ivan Ukhov
  email: ivan.ukhov@gmail.com
description: >
  Solving problems that a software engineer might encounter in practice—or
  invent to sharpen their skills in leisure time
url: https://blog.ivanukhov.com

disqus:
  shortname: good-news-everyone

google_analytics: G-43DGEP382H

exclude:
  - '*.Rmd'
  - .rstudio
  - _caches
  - _scripts

future: true
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

theme: minima
minima:
  date_format: '%B %-d, %Y'
  show_excerpts: true
  social_links:
    - title: GitHub
      icon: github
      url: https://github.com/IvanUkhov
    - title: LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/ivanukhov/
    - title: X
      icon: x-twitter
      url: https://x.com/IvanUkhov
