---
layout: post
title: Sample size determination using historical data and simulation
date: 2019-12-31
math: true
---

In order to be able to test a hypothesis, one has to design and execute an
adequate experiment. Typically, it is neither feasible nor desirable to involve
the entire population in question. Instead, a small yet sufficiently large and
necessarily representative subset of the population is considered, and if done
right, relevant conclusions can then be drawn with respect to the whole
population given the outcome for this small sample. A necessary question to
answer is then, What is the minimal sample size needed? At this point, one might
reach for a thick book in statistics, match the situation at hand with a
statistical test, agree to the terms and conditions of the test, and proceed to
estimating the sample size using the corresponding formulae. In what follows,
however, we shall answer the question posed above without any mathematical
formulae. The only prerequisites are historical data describing the status quo
and the ability to write a few lines of code in a programming language of
choice.

This article is inspired by “[There is only one test!][Allen Downey]” by Allen
Downey and “[Statistics without the agonizing pain][John Rauser]” by John
Rauser.

# Implementation

She sells seashells by the seashore.

```{r, echo = TRUE, message = FALSE}
library(tidyverse)

set.seed(42)
theme_set(theme_minimal())

data <- tibble(value = rlnorm(20000))

metric <- mean
alpha <- 0.05
beta <- 0.2
effect <- 0.1 * metric(data$value)

simulate <- function(n, N) {
  run <- function() {
    replicate(N, { metric(sample(data$value, n, replace = TRUE)) })
  }
  control_null <- run()
  treatment_null <- run()
  control_alternative <- run()
  treatment_alternative <- run() + effect
  effect_null <- treatment_null - control_null
  effect_alternative <- treatment_alternative - control_alternative
  critical_value <- quantile(effect_null, 1 - alpha)
  beta <- mean(effect_alternative < critical_value)
  list(effect_null = effect_null,
       effect_alternative = effect_alternative,
       critical_value = critical_value,
       beta = beta)
}

replication_count <- 1000
search_interval <- c(1, 10000)
target <- function(n) beta - simulate(as.integer(n), replication_count)$beta
sample_size <- as.integer(uniroot(target, interval = search_interval)$root)

result <- simulate(sample_size, replication_count)
tibble(Null = result$effect_null, Alternative = result$effect_alternative) %>%
  gather(group, value) %>%
  ggplot(aes(value, fill = group)) +
  geom_density(alpha = 0.5, color = NA) +
  geom_vline(xintercept = result$critical_value, linetype = 'dashed') +
  labs(x = 'Effect size', y = 'Sampling distribution') +
  theme(legend.title = element_blank())
```

# Conclusion

She sells seashells by the seashore.

# Acknowledgments

I would like to thank [Aaron Rendahl] for the help with the implementation.

[Aaron Rendahl]: http://users.stat.umn.edu/~rend0020/
[Allen Downey]: http://allendowney.blogspot.com/2011/05/there-is-only-one-test.html
[John Rauser]: https://www.youtube.com/watch?v=5Dnw46eC-0o
